= Lab 5 - Introspection, Monitoring, and Metrics using Spring Boot Actuator


== Set up the Actuator

. Change to the lab directory:
+
----
cd $COURSE_HOME/session_05/lab_05/initial/hello-spring-boot
----

. Import the project's `pom.xml` into your editor/IDE of choice.

. To `pom.xml` add the following dependency to include the starter for Spring Boot Actuator:
+
----
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

== Introspection Endpoints

. Run the application:
+
----
./mvnw spring-boot:run
----

. Try out the following endpoints. The output is omitted here because it can be quite large:
+
http://localhost:8080/actuator/beans:: Dumps all of the beans in the Spring context.
http://localhost:8080/actuator/configprops:: Displays a collated list of all `@ConfigurationProperties`.
http://localhost:8080/actuator/env:: Dumps the application's shell environment as well as all Java system properties.
http://localhost:8080/actuator/mappings:: Dumps all URI request mappings and the controller methods to which they are mapped.
http://localhost:8080/actuator/threaddump:: Performs a thread dump.
http://localhost:8080/actuator/httptrace:: Displays trace information (by default the last few HTTP requests).

== Build and Version Control Info

Spring Boot provides an endpoint (http://localhost:8080/actuator/info) that allows the exposure of arbitrary metadata.

One thing that it does well is expose information about the specific build and version control coordinates for a given deployment.

. Add the following plugin to your Maven build.
It will add Git branch and commit coordinates to the `/actuator/info` endpoint:
+
----
<plugin>
	<groupId>pl.project13.maven</groupId>
	<artifactId>git-commit-id-plugin</artifactId>
	<configuration>
	<dotGitDirectory>../../../../.git</dotGitDirectory>
	</configuration>
</plugin>
----
+
*NOTE: The path `../../../../.git` refers to the `.git` directory at the root of the course materials.*

. Add the following properties to `src/main/resources/application.yml` after the `greeting: Hello` line:
+
----
info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
----
+
These will add the project's Maven coordinates to the `/actuator/info` endpoint. The Spring Boot Maven plugin will cause them to automatically be replaced in the assembled JAR.

. Run the application:
+
----
./mvnw spring-boot:run
----

. Visit the application in the browser (http://localhost:8080/actuator/info), and verify that the output is similar to the following:
+
----
{
  build: {
    artifact: "hello-spring-boot",
    name: "hello-spring-boot",
    description: "Hello Spring Boot",
    version: "0.0.1-SNAPSHOT"
  },
  git: {
    branch: "master",
    commit: {
      id: "a15f771",
      time: "2015-05-03T16:51:31-0400"
    }
  }
}
----

== Health Indicators

Spring Boot provides an endpoint (http://localhost:8080/actuator/health) that allows for the notion of various health indicators.

. Normally, when Spring Security is not enabled, the `/health` endpoint will only expose an `UP` or `DOWN` value.
To simplify working with the endpoint for this lab, we will turn off its sensitivity.
Add the following to `src/main/resources/application.yml` after `greeting: Hello`:
+
----
endpoints:
  health:
    sensitive: false
----
. Create the class `io.pivotal.spring.hello.FlappingHealthIndicator` and into it paste the following code:
+
----
package io.pivotal.spring.hello;

import java.util.Random;
import org.springframework.boot.actuate.health.Health;
import org.springframework.boot.actuate.health.HealthIndicator;
import org.springframework.stereotype.Component;

@Component
public class FlappingHealthIndicator implements HealthIndicator{

    private Random random = new Random(System.currentTimeMillis());

    @Override
    public Health health() {
        int result = random.nextInt(100);
        if (result < 50) {
            return Health.down().withDetail("flapper", "failure").withDetail("random", result).build();
        } else {
            return Health.up().withDetail("flapper", "ok").withDetail("random", result).build();
        }
    }
}
----
+
This demo health indicator will randomize the health check.

. Run the application:
+
----
./mvnw spring-boot:run
----

. Visit the application in the browser (http://localhost:8080/actuator/health), and verify that the output is similar to the following (and changes randomly!):
+
----
{
  status: "UP",
  flapping: {
    status: "UP",
    flapper: "ok",
    random: 69
  },
  diskSpace: {
    status: "UP",
    free: 113632186368,
    threshold: 10485760
  }
}
----

== Metrics

Spring Boot provides an endpoint (http://localhost:8080/actuator/metrics) that exposes several automatically collected metrics for your application.
It also allows for the creation of custom metrics.

. Create the class `io.pivotal.spring.hello.GreetingService` and into it paste the following code:
+
----
package io.pivotal.spring.hello;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Meter.Type;
import io.micrometer.core.instrument.MeterRegistry;


@Component
public class GreetingService {

    @Value("${greeting}")
    String greeting;

	@Bean
	MeterRegistryCustomizer<MeterRegistry> addCounterRegistry() {
	    return registry -> registry.config().namingConvention().name("counter.services.greeting.invoked", Type.COUNTER);
	}
	
	private final Counter greetingCounter;
	
	public GreetingService(MeterRegistry registry) {       
        this.greetingCounter = registry.counter("counter.services.greeting.invoked");
    }
	
	public String getGreeting() {
		this.greetingCounter.increment();
        return greeting;
    }
	
}
----
+
This class is using Micrometer, which is now integrated into Spring Boot 2.x. This service counts the number of times that the `getGreeting()` method has been invoked.

. Refactor the contents of the class `io.spring.hello.HelloSpringBootApplication`:
+
----
package io.pivotal.spring.hello;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Meter.Type;
import io.micrometer.core.instrument.MeterRegistry;


@Component
public class GreetingService {

    @Value("${greeting}")
    String greeting;

	@Bean
	MeterRegistryCustomizer<MeterRegistry> addCounterRegistry() {
	    return registry -> registry.config().namingConvention().name("counter.services.greeting.invoked", Type.COUNTER);
	}
	
	private final Counter greetingCounter;
	
	public GreetingService(MeterRegistry registry) {       
        this.greetingCounter = registry.counter("counter.services.greeting.invoked");
    }
	
	public String getGreeting() {
		this.greetingCounter.increment();
        return greeting;
    }
	
}
----
+
`hello()` is now delegating the source of the greeting to our newly created `GreetingService`.

. Run the application:
+
----
./mvnw spring-boot:run
----

. Visit the application in the browser (http://localhost:8080) and refresh the page several times.

. Now visit the `/metrics` endpoint (http://localhost:8080/metrics).
Among the autogenerated metrics you should see a `counter` for the `GreetingService` invocations:
+
----
counter.services.greeting.invoked: 16,
----
+
To learn more about the autogenerated metrics, visit http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html.

link:/README.md#course-materials[Course Materials home] 
