:compat-mode:
= Lab 6 - Binding to Spring Cloud Services

[abstract]
--

--
== Creating Service Instances for Order Service Spring Cloud Services Demo Application
> Each of these services takes a few minutes to initialize while creating application instances and other resources to support them. With many users performing the same actions at the same time, please be patient while initialization completes.

. Create the services the demo application depends on, first start with an instance of the config service.
+
----
cf create-service p.config-server standard config-server -c '{"git": { "uri": "https://github.com/stwomack/womack-configrepo" } }'
Creating service instance config-server in org my-org / space development as student20...
OK
----

== Add the Spring Cloud Config dependency to your project

. Make sure you're back in the _Orders Service_ application directory:
+
----
cd $COURSE_HOME/session_03/lab_01/orders-service
----

. Add the config client dependency to your pom.yml:
+
----
  <dependency>
      <groupId>io.pivotal.spring.cloud</groupId>
      <artifactId>spring-cloud-services-starter-config-client</artifactId>
  </dependency>
----

. Create a new endpoint to demonstrate configuration settings, by adding the following class to /src/main/java/com/workshop/OrderServiceApplication.java
+
----
@RefreshScope
@RestController
class MessageRestController {

	@Value("${message}")
	private String message;

	@RequestMapping("/message")
	String getMessage() {
		System.out.println("Message endpoint called");
		return this.message;
	}
}
----
 
. Hint: If you're not using and IDE that will automatically add imports for you, you'll need to add the following include statements to your class:
+
----
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
----

. In src/main/resources/application.properties, add a default message for the boot app to use in the event it cannot fetch a property from the Config Server
+
----
message=Default Message
----

. To validate, your full application.properties file should now look like this:

```
security.basic.enabled=false
management.security.enabled=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MySQL55Dialect
message=Default Message
```

.  Build the application
+
----
./mvnw package
----
.  Push the applications and tell Cloud Foundry not to start the applications
+
----
cf push -b java_buildpack_offline --no-start
----

Note that this time we're adding '-b java_buildpack_offline' in order to speed up the 'detect' phase of the app staging

.  Bind the application to the config server we created at the beginning of this lab
+
----
cf bind-service orders-service config-server
----

.  Start the app and verify that it's no longer getting the default message when the '/message' endpoint is invoked
+
----
cf start orders-service
----
+
Your route should be something similar to this:
----
https://orders-service-delightful-koala.cfapps.io/message
----

And your message should no longer be "Default Message", because the @Value was picked up from the config repo, via the config server.

link:/README.md#course-materials[Course Materials home] | End of SCS Labs
