:compat-mode:
= Lab 6 - Binding to Spring Cloud Services

[abstract]
--

--
== Creating Service Instances for Order Service Spring Cloud Services Demo Application
> Each of these services takes a few minutes to initialize while creating application instances and other resources to support them. With many users performing the same actions at the same time, please be patient while initialization completes.

. Create the services the demo application depends on, first start with an instance of the config service.
+
----
cf create-service p.config-server standard config-server -c '{"git": { "uri": "https://github.com/stwomack/womack-configrepo" } }'
Creating service instance config-server in org my-org / space development as student20...
OK
----

== Add the Spring Cloud Config dependency to your project

. Make sure you're back in the _Orders Service_ application directory:
+
----
cd $COURSE_HOME/session_03/lab_01/orders-service
----

. Add the config client dependency to your pom.yml:
+
----
  <dependency>
      <groupId>io.pivotal.spring.cloud</groupId>
      <artifactId>spring-cloud-services-starter-config-client</artifactId>
  </dependency>
----

. Create a new endpoint to demonstrate configuration settings, by adding the following class to /src/main/java/com/workshop/OrderServiceApplication.java
+
----
@RefreshScope
@RestController
class MessageRestController {

	@Value("${message}")
	private String message;

	@RequestMapping("/message")
	String getMessage() {
		System.out.println("Message endpoint called");
		return this.message;
	}
}
----

. In src/main/resources/application.properties, add a default message for the boot app to use in the event it cannot fetch a property from the Config Server
+
----
message=Default Message
----

. To validate, your full application.properties file should now look like this:

```
security.basic.enabled=false
management.security.enabled=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MySQL55Dialect
message=Default Message
```

.  Build the application
+
----
./mvnw package
----
.  Push the applications and tell Cloud Foundry not to start the applications
+
----
cf push --no-start
----

link:/README.md#course-materials[Course Materials home] | End of SCS Labs
